carousel:
    images: info1.png, info2.png, info3.png, info1.png, info2.png, info3.png
    refresh-cron: 0 */15 * * * *
cloudinary:
    api-key: 512268179821855
    api-secret: ${CLOUDINARY_SECRET}
    cloud-name: doma6noto
log:
    delete-cron: '* */15 * * * *'
server:
    port: 8000
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/project?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    mvc:
        hiddenmethod:
            filter:
                enabled: true
logging:
    level:
         root: info

